version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "ci"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5
